var GAME_LEVELS = [
  ["                                                                                                 ",
   "          yyyyyyyy   y                                         y       yyyyy    yyyyyyy          ",
   "          y      y   y       yyyyyyy        yyyyyy  y    y     y     y          y                ",
   "          y      y   y      y       y      y        y   y      y    y           y                ",
   "          yyyyyyy    y     y         y    y         y y        y    y           yyyyyyy          ",
   "          y          y    y          y    y         y  y       y     y          y                ",
   "          yyyyyyy    y     y        y     yyyyyyyy  y   y      y      yyyyyy    yyyyyyy          ",
   "          y      y   y     yyyyyyyyy y y                                                         ",
   "          y      y  yyyyy                                   o                                  x ",
   "          yyyyyyy                                                                              x ",
   "                                                             o                                 x ",
   "                                                           xxxxx   xxx       o              o  x ",
   "  xx                              o                   xxx                xxxxx                 x ",
   "  x                         xxxxxxxxxxxx    xxxxxxxx                                        o  x ",
   "  x                   o     x          x    x      x                           xxxx   xxxxxxxxxx ",
   "  x                  xxxxxx            x!!!!x      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          ",
   "  x  @               x                 xxxxxx      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          ",
   "  xxxxxxxxxx     xxxx                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          ",
   "           x!!!!!x                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          ",
   "           xxxxxxx                                                                               ",
   "                                                                                                 ",
   "                                                                                                 ",
   "                                                                                                 "],
  ["                                                                              ",
   "                                                                              ",
   "      y                                                                       ",
   "    y   y                                                                     ",
   "  y   @   y                                                                   ",
   " y   xxx   y                                                                  ",
   "                                                                              ",
   "                                                                              ",
   "         v                                                                    ",
   "                                                                              ",
   "              o                                                               ",
   "                                                                              ",
   "                                                                     o        ",
   "              o                       xx                        o  xxxx       ",
   "                                 xxxx       o                 xxx yyy         ",
   "                             o  xx                   xxx     xxxxx yy         ",
   "                             xx y                      xx           y         ",
   "              o             xx y                                     y        ",
   "                         xx y                 o               o        y      ",
   "                 xxxxxx                                      xxxx       y   o ",
   "             xxxx y                          o            X  yy               ",
   "!!!!!!!!xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx      xxxx yy                 ",
   "                                               !!!!!!!!!                      "],
  ["                                                                                                                                    ",
   "                                                                                                                                    ",
   "  x @ x                                                     o                                                                       ",
   "  x   x                              xxxxxxxx            xxxxx   |                                                                  ",
   "  x o x                    xxxxxxxxxx                   x      x       x                                                            ",
   "  x o x      xxxxxxxxxxx                     o                 x    o  x       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x o x     x                                 xxxxx            x       x       x                                                   x",
   "  x o x     x                                        xx        x    o  x       x      |                                            x",
   "  x o x     x                           |                      x       x       x                                                   x",
   "  x o xxxxxx                                                   x    o  x       x               |                   |               x",
   "  x                xxxxxx                                xxxxxxx       xxxxxxxxx                          |                 ooooo  x",
   "  x            xxxx     x                             xxx      x    o                                                       ooooo  x",
   "  xxxxxxxxxxxxx         x          o          o   xxxx         x                                                            ooooo  x",
   "                        x!!!!!!xxxxxxx!!!!!!xxxxxx             x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                               x!!!x                                                                ",
   "                                                               x!!!x                                                                "],
  ["                                                                                                              ",
   "                                  o        x                     o                o                           ",
   "        o                   y           y       y       x       yyyyy   x                                     ",
   "                             y         y   x    yyyyyy  xxxxxx  y    y  xxxxxx                      o         ",
   "                              y   y   y    x    y    y  x    x  yyyyy   x     x          o                    ",
   "          o             o      y y y y     x    y    y  x    x  y       x                                     ",
   "                                y   y      x    y    y  x    x  yyyyyyy x                                     ",
   "                                                                                        o                     ",
   "                 o                                  o                                                         ",
   "     o                                                                                                        ",
   "                                 o                                           o                o               ",
   "                     o                         o                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "     @                                                                                                        ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
